import { GetStaticProps } from 'next';
import Head from 'next/head';
import { promises as fs } from "fs";
import HomePage from './components/HomePage';

interface StaticPageProps {
  content: string;
}

export const getStaticProps: GetStaticProps<StaticPageProps> = async () => {
  const file = await fs.readFile(process.cwd() + "/data.txt", "utf8");
  console.log('MAIN PAGE:', file)
  return {
    props: {
      content: file,
    },
    revalidate: 20,
  };
};

function doRevalidate() {
  window.location.reload();
}

export default function Home({ content }: StaticPageProps) {
  return (
    <div>
      <Head>
        <title>Next Pages App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage data={content} revalidate={doRevalidate} />
      </main>
    </div>
  )
}
